### ISSUE TITLE
Slack channel set up

### ISSUE THREAD

**Issue by arwenhutt** [ucsdlib/uc-linked-data#2]
Slack channel for discussion.  UC Tech team might be good if it's paid (so doesn't max out messages).

**Comment by arwenhutt** [comment]
I verified that the UC Tech team is a paid account.  
So I went ahead and set up a channel #linked-data-group in the uctech.slack.com team.

@chrissyrissmeyer, @katstine, and @ngeraci I added you since you were already on the team

**Comment by chrissyrissmeyer** [comment]
Since this came up on the call yesterday, here is more information on how to adjust your notification preferences in Slack:

- [General notification guide](https://get.slack.help/hc/en-us/articles/201895138-Guide-to-Slack-notifications)
- [Adjusting channel notification preferences](https://get.slack.help/hc/en-us/articles/201649323-Channel-notification-preferences)
- [Muting a channel](https://get.slack.help/hc/en-us/articles/204411433-Mute-a-channel)
